server:
  port: 8080

spring:
  mvc:
    async:
      request-timeout: 600000
  application:
    name: student-webui-service

student:
  service:
    url: http://localhost:8088
    download-endpoint: /api/files/download
    download-bytes-endpoint: /api/files/download-bytes
    download-resource-endpoint: /api/files/download-bytes

logging:
  level:
    com.student.webui: INFO
    reactor.netty: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
